image: ruby:2.4.1

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - gem install jekyll bundler
    - npm install
    - node --version
    - npm --version

pages:
    stage: deploy
    script:
        - npm run deploy
    artifacts:
        paths:
            - public
    only:
        - master
